#title
title: theForger
# Header
menu:
    主页 : /
    关于 : /about
    分类 : /tags
    归档 : /archives
# title
header:
    aboutHeader: Chat
    aboutInformation: Social
    aboutFriendlink: Talent

# author chat
chat:
十里长亭霜满天，青丝白发度何年。
今生无悔今生错，来世有缘来世迁。
笑靥如花堪缱绻，容颜似水怎缠绵。
情浓渺恰相思淡，自在蓬山舞复跹。

# SubNav
subnav:
  GitHub: "https://github.com/israel-Liu"
  WeChat: "https://www.zhihu.com/people/yang-zi-zi-1995"

# friendlink
friendlink:
    安北北9的直播间: https://live.bilibili.com/1271095
# read more
excerpt_link: ...continue reading

# favicon
favicon: https://github.com/israel-Liu/theForger/raw/master/images/hinata.jpeg

# Baidu Analytics
# baidu_analytics: c21994907883f37ffd80e13627dd4faa

# Google Analytics
google_analytics: UA-75314797-1

# comments
disqus: theForger
# duoshuo: yzzting

# photo link
aboutPhoto: https://github.com/israel-Liu/theForger/raw/master/images/me.jpg
tagPhoto: https://github.com/israel-Liu/theForger/raw/master/images/hinata.jpeg
archivePhoto: https://github.com/israel-Liu/theForger/raw/master/images/One_Piece.jpg

# Blog main color
# Default | Mint Green | Pale Denim | Hot Pink | Dark Violet
blog-color: Pale Denim

# Blog code theme
# Default | Night | Eighties | Blue | Bright
code-theme: Default
